/**
 * NIP-44 v2 reference implementation. Vendored from:
 *
 *   https://github.com/paulmillr/nip44/blob/8205ff7e7fd4e8309bbba43ca45a6baa00c3ec5e/javascript/index.ts
 *
 * Author:  Paul Miller — NIP-44 spec author.
 * Licence: The Unlicense (public domain). https://unlicense.org
 *
 * This file is the cryptography. It is intentionally domain-agnostic: it imports nothing from
 * `domain/` or `application/` but the strict UTF-8 reader of divergence (5), throws plain `Error`, and exposes the
 * same shape as upstream.
 * The user-facing codec at `src/infrastructure/crypto/nip44-codec.ts` checks the caller's keys
 * and remaps this file's plain `Error`s into `Nip44CryptoError`. **Do not edit this file to add validation or
 * domain-typed signatures — that belongs in the codec.**
 *
 * Divergences from the upstream snapshot, exhaustively (so a future audit can verify):
 *   1. Import paths track `@noble/hashes` v2 — `@noble/hashes/sha2` instead of `/sha256`,
 *      `abytes` instead of `ensureBytes`.
 *   2. `u.unpad` reads its U16 length via `new DataView(padded.buffer, padded.byteOffset,
 *      padded.byteLength)` rather than `new DataView(padded.buffer)`. Upstream's form ignores
 *      the subarray byte offset and silently reads from offset 0 of the underlying buffer; the
 *      bug is dormant only because noble's chacha20 currently returns offset-0 outputs. The
 *      fix is conservative and matches the intent of the surrounding `padded.subarray(2, …)`.
 *   3. `getConversationKey` passes the HKDF salt as bytes (`HKDF_SALT_BYTES`) rather than as
 *      the string `"nip44-v2"`. Upstream's string form relied on noble v1 accepting a string;
 *      noble v2's `hkdf_extract` requires `Uint8Array`. The salt bytes are identical.
 *   4. `getConversationKey` decodes the `"02" + pubkeyB` compressed-point form into a 33-byte
 *      `Uint8Array` via `hexToBytes` before handing it to `secp256k1.getSharedSecret`. Upstream
 *      passes the concatenated hex string directly; noble v2 requires bytes. The compressed
 *      point is identical.
 *   5. `u.utf8Decode` reads the plaintext through the library's strict reader, `decodeUtf8`, rather
 *      than a default `TextDecoder`, and throws a plain `Error` when the bytes are not valid UTF-8.
 *      Upstream's decoder strips a leading byte order mark and replaces invalid bytes with U+FFFD;
 *      NIP-44's plaintext is a UTF-8 string, so a plaintext that is not one is refused, and one that
 *      is comes back exactly as written (shared ADR-0100). This is the one import from `domain/`.
 *   6. NIP-44's extended length format (nostr-protocol/nips#1907, merged 2026-06-28), which upstream at the pinned
 *      commit and at its latest commit predates. A plaintext of 65536 bytes or more, up to 4294967295, is prefixed
 *      with two zero bytes and a big-endian u32 instead of the u16 (`u.pad`, the added `u.writeU32BE`, with
 *      `u.writeU16BE` now bounded below 65536), and `u.unpad` reads that prefix when the u16 is zero, refusing one
 *      that names a length under 65536. `u.pad` first applies the NIP pseudocode's range check, refusing a plaintext
 *      outside 1 to 4294967295 bytes with "invalid plaintext size: must be between 1 and 4294967295 bytes", before
 *      it chooses a prefix. `maxPlaintextSize` rises to 4294967295 and `u.decodePayload` drops its 87472-character
 *      and 65603-byte ceilings, which only the u16 prefix implied; the ceiling a host applies is the codec's
 *      (shared ADR-0102). `u.calcPaddedLen` computes its power of two with `2 **` rather than `1 <<`, which
 *      overflows a 32-bit integer past 2^30. The algorithm is the one the NIP's pseudocode gives and nostr-tools
 *      2.25.2 ships, and is pinned by the NIP's extended length prefix vectors.
 *   7. `u.unpad` refuses a padded plaintext whose padding bytes are not all zero, with "invalid padding". NIP-44's
 *      decryption step 7 says "Verify that calculated padding from step 3 of the encryption process matches the actual
 *      padding"; upstream compares only the padding's length, so a MAC-valid payload with non-zero padding decrypts.
 *      This file reads "matches" as the bytes too, the zero bytes `u.pad` writes, as innis/nostr-core does, so both
 *      libraries refuse the same payloads (shared ADR-0102).
 *   8. `u.decodePayload` reads the `#` version flag before the 132-character minimum, so a payload starting with `#`
 *      is reported as "unknown encryption version" whatever its length; upstream checks the length first and reports
 *      a short one as "invalid payload length". NIP-44 says such a payload MUST be reported as an unsupported version.
 *      The maximum length is still checked first, by the codec, before any character is read (shared ADR-0102,
 *      local ADR-0035).
 *
 * No other edits. Algorithm, structure, function names, and encryption outputs are byte-identical to upstream for every
 * plaintext of 1 to 65535 bytes; decryption differs only as divergences (5) to (8) state.
 */

import { chacha20 } from "@noble/ciphers/chacha"
import { equalBytes } from "@noble/ciphers/utils"
import { secp256k1 } from "@noble/curves/secp256k1"
import { expand as hkdf_expand, extract as hkdf_extract } from "@noble/hashes/hkdf"
import { hmac } from "@noble/hashes/hmac"
import { sha256 } from "@noble/hashes/sha2"
import { abytes, concatBytes, hexToBytes, randomBytes, utf8ToBytes } from "@noble/hashes/utils"
import { base64 } from "@scure/base"
import { decodeUtf8 } from "../../domain/service/text-codec.ts"

// Divergence (3): noble v2 `hkdf_extract` requires a Uint8Array salt; upstream passes a string.
const HKDF_SALT_BYTES = utf8ToBytes("nip44-v2")

const u = {
  minPlaintextSize: 0x0001, // 1b msg => padded to 32b
  // Divergence (6): NIP-44's extended length format raises the maximum from 0xffff.
  maxPlaintextSize: 0xffffffff, // 4294967295 (4gb-1) => padded to 4gb
  extendedPrefixThreshold: 0x10000, // 65536 and over => 6-byte prefix

  utf8Encode: utf8ToBytes,
  // Divergence (5): strict, keeping a byte order mark; upstream's `new TextDecoder()` is lossy.
  utf8Decode(bytes: Uint8Array): string {
    const text = decodeUtf8(bytes)
    if (text === null) throw new Error("invalid utf-8")
    return text
  },

  getConversationKey(privkeyA: Uint8Array, pubkeyB: string): Uint8Array {
    const sharedX = secp256k1.getSharedSecret(privkeyA, hexToBytes("02" + pubkeyB)).subarray(1, 33)
    return hkdf_extract(sha256, sharedX, HKDF_SALT_BYTES)
  },

  getMessageKeys(conversationKey: Uint8Array, nonce: Uint8Array): {
    chacha_key: Uint8Array
    chacha_nonce: Uint8Array
    hmac_key: Uint8Array
  } {
    abytes(conversationKey, 32)
    abytes(nonce, 32)
    const keys = hkdf_expand(sha256, conversationKey, nonce, 76)
    return {
      chacha_key: keys.subarray(0, 32),
      chacha_nonce: keys.subarray(32, 44),
      hmac_key: keys.subarray(44, 76),
    }
  },

  calcPaddedLen(len: number): number {
    if (!Number.isSafeInteger(len) || len < 1) throw new Error("expected positive integer")
    if (len <= 32) return 32
    // Divergence (6): `2 **` stays exact past 2^30, where upstream's `1 <<` overflows.
    const nextPower = 2 ** (Math.floor(Math.log2(len - 1)) + 1)
    const chunk = nextPower <= 256 ? 32 : nextPower / 8
    return chunk * (Math.floor((len - 1) / chunk) + 1)
  },

  writeU16BE(num: number): Uint8Array {
    if (!Number.isSafeInteger(num) || num < u.minPlaintextSize || num >= u.extendedPrefixThreshold) {
      throw new Error("invalid plaintext size: must be between 1 and 65535 bytes")
    }
    const arr = new Uint8Array(2)
    new DataView(arr.buffer).setUint16(0, num, false)
    return arr
  },

  // Divergence (6): the extended format's u32 length.
  writeU32BE(num: number): Uint8Array {
    if (!Number.isSafeInteger(num) || num < u.extendedPrefixThreshold || num > u.maxPlaintextSize) {
      throw new Error("invalid plaintext size: must be between 65536 and 4294967295 bytes")
    }
    const arr = new Uint8Array(4)
    new DataView(arr.buffer).setUint32(0, num, false)
    return arr
  },

  pad(plaintext: string): Uint8Array {
    const unpadded = u.utf8Encode(plaintext)
    const unpaddedLen = unpadded.length
    // Divergence (6): the NIP's range check, before choosing a prefix; two zero bytes and a u32 for 65536 or more.
    if (unpaddedLen < u.minPlaintextSize || unpaddedLen > u.maxPlaintextSize) {
      throw new Error("invalid plaintext size: must be between 1 and 4294967295 bytes")
    }
    const prefix = unpaddedLen >= u.extendedPrefixThreshold
      ? concatBytes(new Uint8Array(2), u.writeU32BE(unpaddedLen))
      : u.writeU16BE(unpaddedLen)
    const suffix = new Uint8Array(u.calcPaddedLen(unpaddedLen) - unpaddedLen)
    return concatBytes(prefix, unpadded, suffix)
  },

  unpad(padded: Uint8Array): string {
    // Divergence (2): explicit byte offset; upstream uses `new DataView(padded.buffer)` which
    // ignores `padded.byteOffset` and silently reads from offset 0 of the underlying buffer.
    const view = new DataView(padded.buffer, padded.byteOffset, padded.byteLength)
    // Divergence (6): a zero u16 announces the extended format's u32, which must name 65536 or more.
    const firstTwo = view.getUint16(0)
    const extended = firstTwo === 0
    const unpaddedLen = extended ? view.getUint32(2) : firstTwo
    const prefixLen = extended ? 6 : 2
    if (extended && unpaddedLen < u.extendedPrefixThreshold) throw new Error("invalid padding")
    const unpadded = padded.subarray(prefixLen, prefixLen + unpaddedLen)
    if (
      unpaddedLen < u.minPlaintextSize ||
      unpaddedLen > u.maxPlaintextSize ||
      unpadded.length !== unpaddedLen ||
      padded.length !== prefixLen + u.calcPaddedLen(unpaddedLen)
    ) {
      throw new Error("invalid padding")
    }
    // Divergence (7): the padding must be the zero bytes `pad` writes.
    if (padded.subarray(prefixLen + unpaddedLen).some((byte) => byte !== 0)) throw new Error("invalid padding")
    return u.utf8Decode(unpadded)
  },

  hmacAad(key: Uint8Array, message: Uint8Array, aad: Uint8Array): Uint8Array {
    if (aad.length !== 32) throw new Error("AAD associated data must be 32 bytes")
    const combined = concatBytes(aad, message)
    return hmac(sha256, key, combined)
  },

  // metadata: always 65b (version: 1b, nonce: 32b, max: 32b)
  // plaintext: 1b to 0xffffffff
  // padded plaintext (small, <65536): 32b to 0x10000, with 2b prefix
  // padded plaintext (large, >=65536): 0x10000 to 0x100000000, with 6b prefix
  // raw payload: 99 (65+32+2) to 4294967367 (65+0x100000000+6)
  // compressed payload (base64): 132b and up
  // Divergence (6): no upper ceiling; the u16 prefix's 87472 and 65603 no longer hold. The codec refuses a payload
  // over the host's ceiling before this runs.
  decodePayload(payload: string): { nonce: Uint8Array; ciphertext: Uint8Array; mac: Uint8Array } {
    if (typeof payload !== "string") throw new Error("payload must be a valid string")
    // Divergence (8): the version flag is read before the minimum length.
    if (payload[0] === "#") throw new Error("unknown encryption version")
    const plen = payload.length
    if (plen < 132) throw new Error("invalid payload length: " + plen)
    let data: Uint8Array
    try {
      data = base64.decode(payload)
    } catch (error) {
      throw new Error("invalid base64: " + (error instanceof Error ? error.message : String(error)))
    }
    const dlen = data.length
    if (dlen < 99) throw new Error("invalid data length: " + dlen)
    const vers = data[0]
    if (vers !== 2) throw new Error("unknown encryption version " + vers)
    return {
      nonce: data.subarray(1, 33),
      ciphertext: data.subarray(33, -32),
      mac: data.subarray(-32),
    }
  },
}

function encrypt(plaintext: string, conversationKey: Uint8Array, nonce: Uint8Array = randomBytes(32)): string {
  const { chacha_key, chacha_nonce, hmac_key } = u.getMessageKeys(conversationKey, nonce)
  const padded = u.pad(plaintext)
  const ciphertext = chacha20(chacha_key, chacha_nonce, padded)
  const mac = u.hmacAad(hmac_key, ciphertext, nonce)
  return base64.encode(concatBytes(new Uint8Array([2]), nonce, ciphertext, mac))
}

function decrypt(payload: string, conversationKey: Uint8Array): string {
  const { nonce, ciphertext, mac } = u.decodePayload(payload)
  const { chacha_key, chacha_nonce, hmac_key } = u.getMessageKeys(conversationKey, nonce)
  const calculatedMac = u.hmacAad(hmac_key, ciphertext, nonce)
  if (!equalBytes(calculatedMac, mac)) throw new Error("invalid MAC")
  const padded = chacha20(chacha_key, chacha_nonce, ciphertext)
  return u.unpad(padded)
}

export const v2 = {
  utils: u,
  encrypt,
  decrypt,
}
