/**
 * NIP-44 v2 reference implementation. Vendored from:
 *
 *   https://github.com/paulmillr/nip44/blob/8205ff7e7fd4e8309bbba43ca45a6baa00c3ec5e/javascript/index.ts
 *
 * Author:  Paul Miller — NIP-44 spec author.
 * Licence: The Unlicense (public domain). https://unlicense.org
 *
 * This file is the cryptography. It is intentionally domain-agnostic: it imports nothing from
 * `domain/` or `application/`, throws plain `Error`, and exposes the same shape as upstream.
 * The user-facing wrapper at `src/infrastructure/adapter/nip44-adapter.ts` validates inputs and
 * remaps thrown errors into `Nip44CryptoError`. **Do not edit this file to add validation or
 * domain-typed signatures — that belongs in the adapter.**
 *
 * Divergences from the upstream snapshot, exhaustively (so a future audit can verify):
 *   1. Import paths track `@noble/hashes` v2 — `@noble/hashes/sha2` instead of `/sha256`,
 *      `abytes` instead of `ensureBytes`.
 *   2. The upstream `randomBytes` import from `@noble/hashes/utils` was removed in noble v2;
 *      we inline an equivalent `crypto.getRandomValues` call as the `encrypt` nonce default.
 *   3. `u.unpad` reads its U16 length via `new DataView(padded.buffer, padded.byteOffset,
 *      padded.byteLength)` rather than `new DataView(padded.buffer)`. Upstream's form ignores
 *      the subarray byte offset and silently reads from offset 0 of the underlying buffer; the
 *      bug is dormant only because noble's chacha20 currently returns offset-0 outputs. The
 *      fix is conservative and matches the intent of the surrounding `padded.subarray(2, …)`.
 *   4. `getConversationKey` passes the HKDF salt as bytes (`HKDF_SALT_BYTES`) rather than as
 *      the string `"nip44-v2"`. Upstream's string form relied on noble v1 accepting a string;
 *      noble v2's `hkdf_extract` requires `Uint8Array`. The salt bytes are identical.
 *   5. `getConversationKey` decodes the `"02" + pubkeyB` compressed-point form into a 33-byte
 *      `Uint8Array` via `hexToBytes` before handing it to `secp256k1.getSharedSecret`. Upstream
 *      passes the concatenated hex string directly; noble v2 requires bytes. The compressed
 *      point is identical.
 *
 * No other edits. Algorithm, structure, function names, and outputs are byte-identical to upstream.
 */

import { chacha20 } from "@noble/ciphers/chacha"
import { equalBytes } from "@noble/ciphers/utils"
import { secp256k1 } from "@noble/curves/secp256k1"
import { expand as hkdf_expand, extract as hkdf_extract } from "@noble/hashes/hkdf"
import { hmac } from "@noble/hashes/hmac"
import { sha256 } from "@noble/hashes/sha2"
import { abytes, concatBytes, hexToBytes, utf8ToBytes } from "@noble/hashes/utils"
import { base64 } from "@scure/base"

// Divergence (2): randomBytes is no longer re-exported from `@noble/hashes/utils` in v2.
const randomBytes = (length: number): Uint8Array => crypto.getRandomValues(new Uint8Array(length))

// Divergence (4): noble v2 `hkdf_extract` requires a Uint8Array salt; upstream passes a string.
const HKDF_SALT_BYTES = utf8ToBytes("nip44-v2")

const decoder = new TextDecoder()
const u = {
  minPlaintextSize: 0x0001, // 1b msg => padded to 32b
  maxPlaintextSize: 0xffff, // 65535 (64kb-1) => padded to 64kb

  utf8Encode: utf8ToBytes,
  utf8Decode(bytes: Uint8Array): string {
    return decoder.decode(bytes)
  },

  getConversationKey(privkeyA: Uint8Array, pubkeyB: string): Uint8Array {
    const sharedX = secp256k1.getSharedSecret(privkeyA, hexToBytes("02" + pubkeyB)).subarray(1, 33)
    return hkdf_extract(sha256, sharedX, HKDF_SALT_BYTES)
  },

  getMessageKeys(conversationKey: Uint8Array, nonce: Uint8Array): {
    chacha_key: Uint8Array
    chacha_nonce: Uint8Array
    hmac_key: Uint8Array
  } {
    abytes(conversationKey, 32)
    abytes(nonce, 32)
    const keys = hkdf_expand(sha256, conversationKey, nonce, 76)
    return {
      chacha_key: keys.subarray(0, 32),
      chacha_nonce: keys.subarray(32, 44),
      hmac_key: keys.subarray(44, 76),
    }
  },

  calcPaddedLen(len: number): number {
    if (!Number.isSafeInteger(len) || len < 1) throw new Error("expected positive integer")
    if (len <= 32) return 32
    const nextPower = 1 << (Math.floor(Math.log2(len - 1)) + 1)
    const chunk = nextPower <= 256 ? 32 : nextPower / 8
    return chunk * (Math.floor((len - 1) / chunk) + 1)
  },

  writeU16BE(num: number): Uint8Array {
    if (!Number.isSafeInteger(num) || num < u.minPlaintextSize || num > u.maxPlaintextSize) {
      throw new Error("invalid plaintext size: must be between 1 and 65535 bytes")
    }
    const arr = new Uint8Array(2)
    new DataView(arr.buffer).setUint16(0, num, false)
    return arr
  },

  pad(plaintext: string): Uint8Array {
    const unpadded = u.utf8Encode(plaintext)
    const unpaddedLen = unpadded.length
    const prefix = u.writeU16BE(unpaddedLen)
    const suffix = new Uint8Array(u.calcPaddedLen(unpaddedLen) - unpaddedLen)
    return concatBytes(prefix, unpadded, suffix)
  },

  unpad(padded: Uint8Array): string {
    // Divergence (3): explicit byte offset; upstream uses `new DataView(padded.buffer)` which
    // ignores `padded.byteOffset` and silently reads from offset 0 of the underlying buffer.
    const unpaddedLen = new DataView(padded.buffer, padded.byteOffset, padded.byteLength).getUint16(0)
    const unpadded = padded.subarray(2, 2 + unpaddedLen)
    if (
      unpaddedLen < u.minPlaintextSize ||
      unpaddedLen > u.maxPlaintextSize ||
      unpadded.length !== unpaddedLen ||
      padded.length !== 2 + u.calcPaddedLen(unpaddedLen)
    ) {
      throw new Error("invalid padding")
    }
    return u.utf8Decode(unpadded)
  },

  hmacAad(key: Uint8Array, message: Uint8Array, aad: Uint8Array): Uint8Array {
    if (aad.length !== 32) throw new Error("AAD associated data must be 32 bytes")
    const combined = concatBytes(aad, message)
    return hmac(sha256, key, combined)
  },

  // metadata: always 65b (version: 1b, nonce: 32b, max: 32b)
  // plaintext: 1b to 0xffff
  // padded plaintext: 32b to 0xffff
  // ciphertext: 32b+2 to 0xffff+2
  // raw payload: 99 (65+32+2) to 65603 (65+0xffff+2)
  // compressed payload (base64): 132b to 87472b
  decodePayload(payload: string): { nonce: Uint8Array; ciphertext: Uint8Array; mac: Uint8Array } {
    if (typeof payload !== "string") throw new Error("payload must be a valid string")
    const plen = payload.length
    if (plen < 132 || plen > 87472) throw new Error("invalid payload length: " + plen)
    if (payload[0] === "#") throw new Error("unknown encryption version")
    let data: Uint8Array
    try {
      data = base64.decode(payload)
    } catch (error) {
      throw new Error("invalid base64: " + (error instanceof Error ? error.message : String(error)))
    }
    const dlen = data.length
    if (dlen < 99 || dlen > 65603) throw new Error("invalid data length: " + dlen)
    const vers = data[0]
    if (vers !== 2) throw new Error("unknown encryption version " + vers)
    return {
      nonce: data.subarray(1, 33),
      ciphertext: data.subarray(33, -32),
      mac: data.subarray(-32),
    }
  },
}

function encrypt(plaintext: string, conversationKey: Uint8Array, nonce: Uint8Array = randomBytes(32)): string {
  const { chacha_key, chacha_nonce, hmac_key } = u.getMessageKeys(conversationKey, nonce)
  const padded = u.pad(plaintext)
  const ciphertext = chacha20(chacha_key, chacha_nonce, padded)
  const mac = u.hmacAad(hmac_key, ciphertext, nonce)
  return base64.encode(concatBytes(new Uint8Array([2]), nonce, ciphertext, mac))
}

function decrypt(payload: string, conversationKey: Uint8Array): string {
  const { nonce, ciphertext, mac } = u.decodePayload(payload)
  const { chacha_key, chacha_nonce, hmac_key } = u.getMessageKeys(conversationKey, nonce)
  const calculatedMac = u.hmacAad(hmac_key, ciphertext, nonce)
  if (!equalBytes(calculatedMac, mac)) throw new Error("invalid MAC")
  const padded = chacha20(chacha_key, chacha_nonce, ciphertext)
  return u.unpad(padded)
}

export const v2 = {
  utils: u,
  encrypt,
  decrypt,
}
